trigger: none

pool:
  name: 'Capstone-VM'

steps:

- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
  displayName: 'Set up Python Environment'

